import {
    mdiPencil,
    mdiTrashCan,
    mdiPlus,
    mdiEye,
    mdiAccount,
    mdiPlusCircleOutline,
    mdiArrowLeft,
    mdiCalendarRange,
    mdiClockOutline,
    mdiInformationOutline,
    mdiCameraOutline,
    mdiCctv,
    mdiWhatsapp,
    mdiRadioHandheld,
    mdiGestureTap,
    mdiPhoneInTalkOutline,
    mdiMapMarkerRadiusOutline,
    mdiEyeOutline,
    mdiEyeOffOutline,
    mdiCloseCircleOutline,
    mdiLockReset,
    mdiAccountKey,
    mdiAccountGroup,
    mdiNoteAlertOutline,
    mdiPaperclip,
    mdiHandcuffs
} from "@mdi/js";

export const icons = {
    mdiAccountGroup:mdiAccountGroup,
    mdiAccountKey:mdiAccountKey,
    lockReset: mdiLockReset,
    edit: mdiPencil,
    delete: mdiTrashCan,
    add: mdiPlus,
    view: mdiEye,
    user: mdiAccount,
    plus: mdiPlusCircleOutline,
    arrowLeft: mdiArrowLeft,
    calendar: mdiCalendarRange,
    clock: mdiClockOutline,
    information: mdiInformationOutline,
    camera: mdiCameraOutline,
    cameraCctv: mdiCctv,
    wsp: mdiWhatsapp,
    radio: mdiRadioHandheld,
    btnPanic: mdiGestureTap,
    callPhone: mdiPhoneInTalkOutline,
    map: mdiMapMarkerRadiusOutline,
    eye: mdiEyeOutline,
    eyeOff: mdiEyeOffOutline,
    close: mdiCloseCircleOutline,
    mdiNoteAlertOutline:mdiNoteAlertOutline,
    attach: mdiPaperclip,
    mdiHandcuffs:mdiHandcuffs
};
